@startuml
class Singleton {
  - {static} instance: Singleton
  - Singleton()
  + {static} getInstance(): Singleton
}
note right of Singleton::getInstance #LightBlue
if (instance == null) {
    instance = new Singleton()
   }
  return instance
end note
class Client {}

Client -> Singleton: getInstance

hide empty fields
hide empty methods

skinparam class {
  BackgroundColor LightYellow
  BorderColor DarkSlateGray
  ArrowColor DarkSlateGray
  FontColor DarkSlateGray
}
@enduml
